title: acfirth
description: My personal blog for all of my cybersecurity related posts. Writeups, CVEs, Custom Tools...
baseurl: ""
url: "https://acfirth.com"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    default_lang: text
    bold_every: 10
    guess_lang: true

highlighter: rouge

rouge:
  theme: dracula

theme: null

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  writeups:
    output: true
    permalink: /writeups/:title/
  tools:
    output: true
    permalink: /tools/:title/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: writeups
    values:
      layout: post
  - scope:
      path: ""
      type: tools
    values:
      layout: post